import java.util.HashMap;

public class findTheDiff {
    // You are given two strings s and t.
    // String t is generated by random shuffling string s and then add one more
    // letter at a random position.

    // Return the letter that was added to t.
    public static void main(String[] args) {
        String s = "ae";
        String t = "aea";
        System.out.println(findTheDifference(s, t));

    }

    public static char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<>();
        for(int i = 0; i < t.length(); i++){
            char ch = t.charAt(i);
            map.put(ch, map.getOrDefault(ch, 0) + 1);
        }

        for(int i = 0; i < s.length(); i++){
            char ch = s.charAt(i);
            // map.put(ch, map.getOrDefault(ch, 0) + 1);
            if(map.containsKey(ch)){
               map.put(ch, map.get(ch) - 1);
            }
        }

        char ch = 'a' ;
        for(Character keys : map.keySet()){
            if(map.get(keys) > 0){
                ch = keys;
            }
        }
        
        return ch;
    }
}
